version: '3.3'

services:

  web:
    build: ./
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    volumes:
      - ./:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - "8000:8004"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
    postgres_data: