[tool.poetry]
name = "dev"
version = "0.1.0"
description = ""
authors = ["en9er"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
