name: CI/CD for FastAPI in Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Build and test Docker image
        run: |
          docker-compose up --build

      - name: Deploy to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-fastapi-app ${{ secrets.DOCKERHUB_USERNAME }}/livepoll-api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/livepoll-api
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
