name: Docker Compose on Tag

on:
  push:
    tags:
      - '*'

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        # Install Docker Compose
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose --version
      shell: bash

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
      working-directory: .

